name: Compile all example PDFs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          lfs: true
          submodules: true

      - name: Compile colorful-dream
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: colorful-dream
          root_file: example.tex
          pre_compile: |
            ln ../example.bib ./example.bib
            ln ../exampletitleimage.png ./exampletitleimage.png

      - name: Compile fragment
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: fragment
          root_file: example.tex
          pre_compile: |
            ln ../example.bib ./example.bib
            ln ../exampletitleimage.png ./exampletitleimage.png

      - name: Compile lucy
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: lucy
          root_file: example.tex
          pre_compile: |
            ln ../example.bib ./example.bib
            ln ../exampletitleimage.png ./exampletitleimage.png

      - name: Compile dividing-lines
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: dividing-lines
          root_file: example.tex
          pre_compile: |
            ln ../example.bib ./example.bib
            ln ../exampletitleimage.png ./exampletitleimage.png

      - name: Commit PDF
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -f */example.pdf
          git commit -m "Update PDFs by Workflow"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: "gh-pages"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
